import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-grid-slate-100`}>
        <Navbar />
        <div className="bg-gradient-to-b from-transparent to-white">
          {children}
          <footer className="text-center text-gray-400 py-5">
            Copyright © {new Date().getFullYear()}. Make With 💖 By Aung
          </footer>
        </div>
      </body>
    </html>
  );
}
